### ISSUE TITLE
Ordering of @import

### ISSUE THREAD

**Issue by jpsc** [lightningtgc/cssorder#1]
Hello.

First of all this is a very useful sublime package. Congrats.

But there is and issue that sort makes it unusable. Not sure if because using scss @import or if there are a way to change this on the config.

``` scss
.bottom-navigation {
    @include susy-breakpoint($bp-medium) {
        li {
            display: inline-block;
        }
    }
    ul {
        padding-left: 0;
    }

    li {
            margin-bottom: 1rem;
    }

   //@include was saved here and moves to the top;

}
```

As you can see by the example, saving the include on the bottom of the nesting moves it to the top. This is not ideal because it will change the css output.

Is this something that can be fixed, or its just out of scope for the project because its sass related ?
